plugins {
    id 'kotlin-parcelize'
    alias(libs.plugins.sqldelight)
}

android {
    namespace 'com.savvasdalkitsis.uhuruphotos.feature.db.domain.api'
}

sqldelight {
    databases {
        Database {
            packageName = "com.savvasdalkitsis.uhuruphotos.feature.db.domain.api"
        }
    }
}

dependencies {

    implementation(
            libs.hilt,
            libs.sqldelight.android,
            libs.sqldelight.coroutines,
            project(":feature:media:common:domain:api"),
            project(":feature:media:local:domain:api"),
            project(":feature:people:view:api"),
            project(":feature:upload:domain:api"),
            project(":foundation:coroutines:api"),
            project(":foundation:lang:api"),
    )
}

afterEvaluate {
    tasks.configureEach { task ->
        if (task.name.startsWith("ksp") && task.name.endsWith("Kotlin")) {
            def variantName = task.name.substring(3, task.name.length() - 6)
            def sqlTaskName = "generate${variantName}DatabaseInterface"
            def sqlTask = tasks.findByName(sqlTaskName)
            if (sqlTask != null) {
                task.dependsOn(sqlTask)
                println "Fixed dependency: ${task.name} depends on ${sqlTaskName}"
            }
        }
    }
}