default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Tag and deploy a new internal release"
  lane :deploy do
    gradle(
        task: "bundle",
        build_type: "release"
    )

    upload_to_play_store(
        json_key: ENV["ANDROID_JSON_KEY_FILE"],
        track: "internal",
        skip_upload_metadata: true,
        skip_upload_changelogs: false,
        skip_upload_images: true,
        skip_upload_screenshots: true
    )

    set_github_release(
        repository_name: "savvasdalkitsis/uhuruphotos-android",
        api_bearer: ENV["GITHUB_TOKEN"],
        name: "Release " + last_git_tag,
        tag_name: last_git_tag,
        description: (File.read("fastlane/metadata/android/en-GB/changelogs/" + android_get_version_code + ".txt") rescue "No changelog provided"),
        commitish: "main",
        upload_assets: ["app/build/outputs/bundle/release/app-release.aab"]
    )
  end
end
