/*
Copyright 2023 Savvas Dalkitsis

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */
package com.savvasdalkitsis.uhuruphotos.feature.lightbox.view.implementation.ui.info

import com.savvasdalkitsis.uhuruphotos.foundation.icons.api.R.drawable.*

object LightboxCaptionIcons {

    val icons = mapOf(
        "airfield" to ic_airport,
        "airplane cabin" to ic_airplane,
        "airport terminal" to ic_airport,
        "alcove" to ic_tunnel,
        "alley" to null,
        "amphitheater" to ic_amphitheatre,
        "amusement arcade" to null,
        "amusement park" to null,
        "apartment building outdoor" to ic_apartments,
        "aquarium" to ic_fishbowl,
        "aqueduct" to ic_aqueduct,
        "arcade" to null,
        "arch" to ic_tunnel,
        "archaelogical excavation" to ic_shovel,
        "archive" to ic_archive,
        "arena hockey" to ic_hockey_puck,
        "arena performance" to ic_stadium_outline,
        "arena rodeo" to ic_cowboy,
        "army base" to null,
        "art gallery" to ic_palette,
        "art school" to ic_palette,
        "art studio" to ic_palette,
        "artists loft" to ic_palette,
        "assembly line" to ic_robot_industrial,
        "athletic field outdoor" to ic_soccer_field,
        "atrium public" to null,
        "attic" to null,
        "auditorium" to ic_seat,
        "auto factory" to ic_robot_industrial,
        "auto showroom" to ic_car,
        "badlands" to ic_weather_sunset,
        "bakery shop" to ic_cupcake,
        "balcony exterior" to ic_balcony,
        "balcony interior" to ic_balcony,
        "ball pit" to null,
        "ballroom" to ic_ballroom,
        "bamboo forest" to ic_forest,
        "bank vault" to ic_bank,
        "banquet hall" to ic_ballroom,
        "bar" to ic_wine,
        "barndoor" to ic_barn,
        "baseball field" to ic_baseball,
        "basement" to ic_basement,
        "basketball court indoor" to ic_basketball_hoop,
        "bathroom" to ic_shower,
        "bazaar indoor" to ic_shopping,
        "bazaar outdoor" to ic_shopping,
        "beach" to ic_beach,
        "beach house" to null,
        "beauty salon" to null,
        "bedchamber" to ic_bed,
        "bedroom" to ic_bed,
        "beer garden" to ic_beer,
        "beer hall" to ic_beer,
        "berth" to ic_lifebuoy,
        "biology laboratory" to ic_test_tube,
        "boardwalk" to null,
        "boat deck" to ic_ferry,
        "boathouse" to ic_ferry,
        "bookstore" to ic_book_open,
        "booth indoor" to null,
        "botanical garden" to ic_flower,
        "bow window indoor" to null,
        "bowling alley" to ic_bowling,
        "boxing ring" to ic_boxing_glove,
        "bridge" to ic_bridge,
        "bullring" to ic_cow,
        "burial chamber" to ic_grave_stone,
        "bus interior" to ic_bus,
        "bus station indoor" to ic_bus_stop,
        "butchers shop" to ic_knife,
        "butte" to ic_mountains,
        "cabin outdoor" to null,
        "cafeteria" to ic_coffee,
        "campsite" to ic_tent,
        "campus" to null,
        "canal natural" to null,
        "canal urban" to null,
        "candy store" to ic_candycane,
        "canyon" to ic_mountains,
        "car interior" to ic_car,
        "carrousel" to null,
        "castle" to ic_castle,
        "catacomb" to ic_grave_stone,
        "cemetery" to ic_grave_stone,
        "chalet" to ic_castle,
        "chemistry lab" to ic_test_tube,
        "childs room" to ic_teddy_bear,
        "church indoor" to ic_church,
        "church outdoor" to ic_church,
        "classroom" to ic_person_board,
        "clean room" to null,
        "cliff" to null,
        "closet" to ic_wardrobe,
        "clothing store" to ic_hanger,
        "coast" to null,
        "cockpit" to null,
        "coffee shop" to ic_coffee,
        "computer room" to ic_desktop_classic,
        "conference center" to ic_person_board,
        "conference room" to ic_person_board,
        "construction site" to ic_hard_hat,
        "corn field" to ic_corn,
        "corral" to null,
        "corridor" to null,
        "cottage" to null,
        "courthouse" to ic_gavel,
        "courtyard" to null,
        "creek" to null,
        "crevasse" to null,
        "crosswalk" to ic_crosswalk,
        "dam" to ic_dam,
        "delicatessen" to null,
        "department store" to ic_department,
        "desert road" to null,
        "desert sand" to null,
        "desert vegetation" to ic_cactus,
        "diner outdoor" to null,
        "dining hall" to null,
        "dining room" to null,
        "discotheque" to null,
        "doorway outdoor" to ic_door,
        "dorm room" to null,
        "downtown" to null,
        "dressing room" to ic_hanger,
        "driveway" to ic_road,
        "drugstore" to ic_pills,
        "elevator door" to ic_elevator,
        "elevator lobby" to ic_elevator,
        "elevator shaft" to ic_elevator,
        "embassy" to null,
        "engine room" to null,
        "entrance hall" to null,
        "escalator indoor" to ic_escalator,
        "excavation" to null,
        "fabric store" to null,
        "farm" to ic_barn,
        "fastfood restaurant" to ic_food,
        "field cultivated" to null,
        "field road" to null,
        "field wild" to null,
        "fire escape" to ic_exit_run,
        "fire station" to ic_fire_hydrant,
        "fishpond" to ic_fish,
        "flea market indoor" to null,
        "florist shop indoor" to ic_flower,
        "food court" to ic_food,
        "football field" to ic_soccer_field,
        "forest broadleaf" to ic_forest,
        "forest path" to ic_forest,
        "forest road" to ic_forest,
        "formal garden" to null,
        "fountain" to ic_fountain,
        "galley" to ic_sail_boat,
        "garage indoor" to ic_garage,
        "garage outdoor" to ic_garage,
        "gas station" to ic_gas_station,
        "gazebo exterior" to ic_greenhouse,
        "general store indoor" to ic_store,
        "general store outdoor" to ic_store,
        "gift shop" to ic_gift,
        "glacier" to ic_iceberg,
        "golf course" to ic_golf,
        "greenhouse indoor" to ic_greenhouse,
        "greenhouse outdoor" to ic_greenhouse,
        "grotto" to ic_cave,
        "gymnasium indoor" to ic_dumbbell,
        "hangar indoor" to ic_hangar,
        "hangar outdoor" to ic_hangar,
        "harbor" to ic_wharf,
        "hardware store" to null,
        "hayfield" to null,
        "heliport" to null,
        "highway" to null,
        "home office" to null,
        "home theater" to null,
        "hospital" to null,
        "hospital room" to null,
        "hot spring" to null,
        "hotel outdoor" to null,
        "hotel room" to null,
        "hunting lodge outdoor" to null,
        "ice cream parlor" to null,
        "ice floe" to null,
        "ice shelf" to null,
        "ice skating rink indoor" to null,
        "ice skating rink outdoor" to null,
        "iceberg" to null,
        "igloo" to null,
        "indoor" to null,
        "industrial area" to null,
        "inn outdoor" to null,
        "islet" to null,
        "jacuzzi indoor" to null,
        "jail cell" to null,
        "japanese garden" to null,
        "jewelry shop" to null,
        "junkyard" to null,
        "kasbah" to null,
        "kennel outdoor" to null,
        "kindergarden classroom" to null,
        "kitchen" to null,
        "lagoon" to null,
        "lake natural" to null,
        "landfill" to null,
        "landing deck" to null,
        "laundromat" to null,
        "lawn" to null,
        "lecture room" to null,
        "legislative chamber" to null,
        "library indoor" to null,
        "library outdoor" to null,
        "lighthouse" to null,
        "living room" to null,
        "loading dock" to null,
        "lobby" to null,
        "lock chamber" to null,
        "locker room" to null,
        "mansion" to null,
        "market indoor" to null,
        "market outdoor" to null,
        "marsh" to null,
        "martial arts gym" to null,
        "mausoleum" to null,
        "medina" to null,
        "mezzanine" to null,
        "moat water" to null,
        "mosque outdoor" to null,
        "motel" to null,
        "mountain" to null,
        "mountain path" to null,
        "mountain snowy" to null,
        "movie theater indoor" to null,
        "museum indoor" to null,
        "museum outdoor" to null,
        "music studio" to null,
        "natural history museum" to null,
        "nursery" to null,
        "nursing home" to null,
        "oast house" to null,
        "ocean" to null,
        "office" to null,
        "office building" to null,
        "office cubicles" to null,
        "oilrig" to null,
        "operating room" to null,
        "orchard" to null,
        "orchestra pit" to null,
        "outdoor" to null,
        "pagoda" to null,
        "palace" to null,
        "pantry" to null,
        "park" to null,
        "parking garage indoor" to null,
        "parking garage outdoor" to null,
        "parking lot" to null,
        "pasture" to null,
        "patio" to null,
        "pavilion" to null,
        "pet shop" to null,
        "pharmacy" to null,
        "phone booth" to null,
        "physics laboratory" to null,
        "picnic area" to null,
        "pier" to null,
        "pizzeria" to null,
        "playground" to null,
        "playroom" to null,
        "plaza" to null,
        "porch" to null,
        "promenade" to null,
        "pub indoor" to null,
        "racecourse" to null,
        "raceway" to null,
        "raft" to null,
        "railroad track" to null,
        "rainforest" to null,
        "reception" to null,
        "recreation room" to null,
        "repair shop" to null,
        "residential neighborhood" to null,
        "restaurant" to null,
        "restaurant kitchen" to null,
        "restaurant patio" to null,
        "rice paddy" to null,
        "rock arch" to null,
        "roof garden" to null,
        "rope bridge" to null,
        "ruin" to null,
        "runway" to null,
        "sandbox" to null,
        "sauna" to null,
        "schoolhouse" to null,
        "science museum" to null,
        "server room" to null,
        "shed" to null,
        "shoe shop" to null,
        "shopfront" to null,
        "shopping mall indoor" to null,
        "shower" to null,
        "ski resort" to null,
        "ski slope" to null,
        "sky" to null,
        "skyscraper" to null,
        "slum" to null,
        "snowfield" to null,
        "soccer field" to null,
        "stable" to null,
        "stadium baseball" to null,
        "stadium football" to null,
        "stadium soccer" to null,
        "stage indoor" to null,
        "stage outdoor" to null,
        "staircase" to null,
        "storage room" to null,
        "street" to null,
        "subway station platform" to null,
        "supermarket" to null,
        "sushi bar" to null,
        "swamp" to null,
        "swimming hole" to null,
        "swimming pool indoor" to null,
        "swimming pool outdoor" to null,
        "synagogue outdoor" to null,
        "television room" to null,
        "television studio" to null,
        "temple asia" to null,
        "throne room" to null,
        "ticket booth" to null,
        "topiary garden" to null,
        "tower" to null,
        "toyshop" to null,
        "train interior" to null,
        "train station platform" to null,
        "tree farm" to null,
        "tree house" to null,
        "trench" to null,
        "tundra" to null,
        "underwater ocean deep" to null,
        "utility room" to null,
        "vegetable garden" to null,
        "veterinarians office" to null,
        "viaduct" to null,
        "village" to null,
        "vineyard" to null,
        "volcano" to null,
        "volleyball court outdoor" to null,
        "waiting room" to null,
        "water park" to null,
        "water tower" to null,
        "waterfall" to null,
        "watering hole" to null,
        "wave" to null,
        "wet bar" to null,
        "wheat field" to null,
        "wind farm" to null,
        "windmill" to null,
        "yard" to null,
        "youth hostel" to null,
        "zen garden" to null,
    )
}